## Configuracion de Spring
spring:
  application:
    name: ms-citas
  datasource:
    url: jdbc:mysql://localhost:3306/bdd_clinica
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  signing-key: MaYzkSjmkzPC57L
  encoding-strength: 256
  security-realm: Spring Boot JWT

  jwt:
    client-id: mitomediapp
    client-secret: mito89codex
    grant-type: password
    scope-read: read
    scope-write: write
    resource-ids: mitoresourceid

server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
#para seguridad      
security:
   oauth2:
    resource:
      userInfoUri: http://localhost:9999/user   
      filter-order: 3

springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger-ui-custom.html
  swagger-ui.operationsSorter: method